### ISSUE TITLE
What version of unrar is unpackerr using

### ISSUE THREAD

**Issue by brasse** [davidnewhall/unpackerr#40] opened 2020-05-06 12:31 UTC
Hi! I had unpackerr getting stuck on me on a rar file that i guess it couldn't extract. One episode was stuck in waiting.

2020/05/05 19:05:59 [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]

So I was wondering why? What version of unrar is unpackerr using?

I failed to extract the file with unrar-free on rasbian, but succeeded with the latest version of unrar from: https://www.rarlab.com/rar/unrarsrc-5.9.2.tar.gz

**Comment by davidnewhall** [comment] 2020-05-25 18:07
Sorry missed this issue.... 

`waiting` usually means it's not marked as complete in Sonarr. If you can provide more logs I can deduce further.

**Comment by brasse** [comment] 2020-06-02 11:56
```
2020/06/02 11:51:59 [Sonarr] Updated (http://192.168.2.68:8989): 0 Items Queued
2020/06/02 11:51:59 [Radarr] Updated (http://192.168.2.68:7878): 2 Items Queued
2020/06/02 11:51:59 [Radarr] Completed item still waiting: Black.Hawk.Down.2001.EXTENDED.1080p.BluRay.x264-FLAME, no extractable files found at: /downloads/Black.Hawk.Down.2001.EXTENDED.1080p.BluRay.x264-FLAME
2020/06/02 11:51:59 [Radarr] Completed item still waiting: Argo 2012 10bit hevc-d3g (uhd remux), no extractable files found at: /downloads/Argo 2012 10bit hevc-d3g (uhd remux)
2020/06/02 11:51:59 [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [1 finished]
```

This happened again now. My guess is that for some reason unpackerr can't unpack that rar. I have had similar problems before (without using unpackerr). Then the issue has been that `unrar-free` can't unpack some rar archive. However, the latest `unrar ` from rarlab.com can always unpack. I have not run into an archive that it can't unpack. Could it be the same issue here? What version/distro of `unrar` in `unpackerr` using?

**Comment by davidnewhall** [comment] 2020-06-02 17:41
You haven't provided anything that shows a problem, let alone an error unraring. Unpacker doesn't use unrar, it is unrar, [using this library](https://github.com/nwaples/rardecode).

**Comment by davidnewhall** [comment] 2020-06-02 20:43
`no extractable files found` means that it did not find a `.rar` in the displayed path.

**Comment by Jerrk** [comment] 2020-06-07 13:55
I think i have the same issue with a bunch of titles containing a .rar file in it's directory but it still says no extractable files found.
I had 25 files downloading whereas only 1 imported without issue, the other 24 are all stuck. 

They all have the same naming convetion and contents EXCEPT the completed import LACKS a subfolder with a sample file within. It would seem that is the culprit

I restarted both deluge and unpackerr.



```
2020/06/07 15:42:17 [Lidarr] Updated (http://192.168.1.111:8686): 2 Items Queued
2020/06/07 15:42:17 [Radarr] Updated (http://192.168.1.111:7878): 45 Items Queued
2020/06/07 15:42:17 [Sonarr] Updated (http://192.168.1.111:8989): 106 Items Queued
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E26.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E26.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E07.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E07.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E19.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E19.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E16.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E16.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E02.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E02.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E03.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E03.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E25.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E25.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E20.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E20.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E22.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E22.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E04.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E04.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E06.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E06.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E23.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E23.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E13.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E13.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E18.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E18.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E14.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E14.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E05.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E05.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E11.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E11.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E01.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E01.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E12.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E12.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E24.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E24.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E17.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E17.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E10.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E10.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E09.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E09.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Sonarr] Completed item still waiting: Young.Justice.S01E15.1080p.BluRay.x264-CCAT, no extractable files found at: /mnt/user/Media/.Seeding/Sonarr/Young.Justice.S01E15.1080p.BluRay.x264-CCAT
2020/06/07 15:42:17 [Unpackerr] Queue: [24 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
```
Failed
![](https://i.imgur.com/TnNVDa2.png)
Completed
![](https://i.imgur.com/bfH09OE.png)

**Comment by davidnewhall** [comment] 2020-06-07 21:01
The problem is related to the the mounted folder and `path` variable(s) in the config. Probably a lot easier to troubleshoot your configuration issues on Discord. Find me in @hotio's Discord, here: https://discord.gg/4czsh7K

**Comment by Jerrk** [comment] 2020-06-08 17:49
It was indeed my mistake choosing the correct path, i had initially dismissed that as an option since one of the .rars actually got imported correctly, not sure how that happened.

Changing to the correct download path fixed my issue.

**Comment by davidnewhall** [comment] 2020-06-08 17:52
Unpackerr tries. Sometimes it can overcome a bad config, sometimes it cannot. Glad you got it working!

**Closed by davidnewhall** 2020-06-08 17:52 UTC
