### ISSUE TITLE
Is there a way to disable the suffix _unpackerr added to folders?

### ISSUE THREAD

**Issue by alexbleicker** [davidnewhall/unpackerr#189] opened 2022-04-01 01:39 UTC
Is there a way to disable the suffix _unpackerr added to folders? I could not find any indication this is possible on the documentation. It would be great the extraction could be done keeping the same folder name at a different location without adding _unpackerr to the folder name

**Comment by dtatools** [comment] 2022-04-01 02:43
There is not. The only work around would be to setup a cmd hook that runs a script to rename the folder. 

This is a duplicate of #173, so I'm going to close this out. If you have more questions or want help with the command hook, please head over to this other issue so we can keep the "fix" in one place. Thanks!

**Comment by davidnewhall** [comment] 2022-04-01 02:47
There is not. The only work around would be to setup a cmd hook that runs a script to rename the folder.

This is a duplicate of https://github.com/davidnewhall/unpackerr/issues/173, so I'm going to close this out. If you have more questions or want help with the command hook, please head over to this other issue so we can keep the "fix" in one place. Thanks!

**Closed by davidnewhall** 2022-04-01 02:47 UTC
