### ISSUE TITLE
Few questions about unpackerr

### ISSUE THREAD

**Issue by BRTPOB** [davidnewhall/unpackerr#64] opened 2020-11-22 07:40 UTC
I have been looking at using this tool for a while, but I finally got around to setting it up, and I absolutely love it, but I have a couple of questions in relation to the usage/config.

I know that you can run parallel unpackings instead of serial, but what's the absolute minimum in terms of times you can set for the different sections?

When it says that there were X number of restarts, is there an easy way of seeing what was restarted and why?

The same goes for failures.

What exactly does pre-Queue mean? I'm seeing pre-Queue for stuff that wasn't rared, so I would assume it should just ignor eit, but I'm not seeing that.

Thanks for the awesome tool.

**Comment by davidnewhall** [comment] 2020-11-23 03:07
> What's the absolute minimum in terms of times you can set for the different sections?

I'm sorry, but I'm not sure what you're asking here.

> Is there an easy way of seeing what was restarted and why?

That information is in the logs. Things will only restart if extraction failed. They may restart forever until it's fixed. I have not experienced this behavior much, so if you want to share your logs I'd be happy to have a look. email: david at sleepers dot pro.

> What exactly does pre-Queue mean?

It means the item is still in your Activity Queue, and not being imported. An item staying this way for a long period while `completed` usually means you need to go into your app and manually import the item or remove if from the queue. If an extractable file is found in the item, the item will leave pre-queue and become queued for extraction.

**Comment by BRTPOB** [comment] 2020-11-23 07:37
Sorry, the first question was a mixture of thoughts and should've been clearer. What I meant was, how quickly can each of the time-based options be set to? You mention in the config example that it's all based on Go, so I was trying to understand can you go into the seconds or milliseconds timing or are you limited to just minutes.

The restarts seem to be related to one pack that has a bad rar in them, but I've manually imported those files so I'm curious as to why it keeps trying to unpack and import them.

For the pre-Queue, I see that a lot for non-rared files which is why I'm confused. I'll double check my radarr instance, but I'm pretty sure they're already imported. I will send the log over as well, just so you can take a look at what mine looks like with all of its fun.

**Comment by davidnewhall** [comment] 2020-11-23 09:59
>  How quickly can each of the time-based options be set to?
> What's the absolute minimum in terms of times you can set for the different sections?

These two questions seem like they ask the same thing. Are you referring to configuration options? Which ones? I'm still not understanding what the problem is you're trying to solve with this question. Can you describe the problem?

>  I'm curious as to why it keeps trying to unpack and import them.

It's trying to unpack them, but import them? I don't think it can import them until it gets properly unpacked. You mention a bad archive: this will cause it to keep retrying. It's expecting you to either delete it, or finish downloading it so it's complete.

>  I'll double check my radarr instance, but I'm pretty sure they're already imported.

Radarr v3 hides unknown movies by default, but continues to provide them to API callers. Go into Radarr -> Activity -> Click `Options` in the top right and check the box that says `Show Unknown Movie Items`. Once the unknown movies display in your queue, either manually import them or delete them.

**Comment by BRTPOB** [comment] 2020-11-23 10:06
For the timing thing, I was meaning the config, such as this:

# How long an item must be queued (download complete) before extraction will start.
# One minute is the historic default and works well. Set higher if your downloads
# take longer to finalize (or transfer locally). Uses Go Duration.
start_delay = "30s"

I assumed it would fail after X number of tries, but that makes sense that it'll just keep retrying.

I'm using Radarr v2 and Sonarr v3, and I found the problem which was that in both instances, the movies or TV shows in question were still in the queue even though they had already been imported (hover text said 'Has same file size as existing file') so I just manually imported them and it's happy now.

**Comment by davidnewhall** [comment] 2020-11-23 10:10
oh, `start_delay`. When an items hits `complete` in sonarr or radarr, unpackerr will wait `start_delay` before queuing the item for extraction. I would generally just recommend leaving that at 1 minute, but 30s is probably fine. I think the way things work internally though, it only actually checks every minute, so a minute is probably actual minimum. 

I made this value to be turned UP not DOWN. Some folks run radarr and their download client in different locations and they use a script to copy downloads locally. Sometimes this takes a while and increasing `start_delay` makes it work better.

**Comment by BRTPOB** [comment] 2020-11-23 10:12
Ah, ok, that makes sense. I'm running everything locally, so it's not as much of an issue for me for the start_delay. Overall, though, the tool has been amazing in fixing the major problem I'd been having, which is that Sonarr and Radarr would import the files before they were totally done extracting, so I had to re-import the files after finding out (much later) that they were broken.

**Comment by davidnewhall** [comment] 2020-11-23 10:13
The *arr apps should only attempt to import when your download client makes the transfer as done. Do you know why they would import prematurely? It's not clear how this app will fix that.

**Comment by BRTPOB** [comment] 2020-11-23 10:14
I have no idea, but they were doing it constantly. Since setting this up, I haven't had that problem.

**Comment by davidnewhall** [comment] 2020-11-23 10:23
Interesting. Glad it's working out! :)

**Comment by BRTPOB** [comment] 2020-11-23 13:59
Yeah. New question: is there anyway to copy certain extra files, specifically the .nfo and .srr files into wherever the mkvs are being extracted so they get pulled in at the same time?

**Comment by davidnewhall** [comment] 2020-11-23 19:46
unpackerr moves every file it unpacked from a rar file back into the folder it unrar'd from, unless there is an existing file it may refuse to overwrite.

**Comment by BRTPOB** [comment] 2020-11-24 21:35
I'm seeing it do that for some things, but not all season packs, which is odd. Here's what one looks like right now:

```
offspring@CloudSeedbox:/mnt/local/downloads/torrents/rutorrent/completed/sonarr4k/Bloodline.S02.2160p.WEBRip.X264-DEFLATE$ ls
Bloodline.S02E01.2160p.WEBRip.X264-DEFLATE
Bloodline.S02E01.2160p.WEBRip.X264-DEFLATE.mkv
Bloodline.S02E02.2160p.WEBRip.X264-DEFLATE
Bloodline.S02E02.2160p.WEBRip.X264-DEFLATE.mkv
Bloodline.S02E03.2160p.WEBRip.X264-DEFLATE
Bloodline.S02E03.2160p.WEBRip.X264-DEFLATE.mkv
Bloodline.S02E04.2160p.WEBRip.X264-DEFLATE
Bloodline.S02E04.2160p.WEBRip.X264-DEFLATE.mkv
Bloodline.S02E05.2160p.WEBRip.X264-DEFLATE
Bloodline.S02E05.2160p.WEBRip.X264-DEFLATE.mkv
Bloodline.S02E06.2160p.WEBRip.X264-DEFLATE
Bloodline.S02E06.2160p.WEBRip.X264-DEFLATE.mkv
Bloodline.S02E07.2160p.WEBRip.X264-DEFLATE
Bloodline.S02E07.2160p.WEBRip.X264-DEFLATE.mkv
Bloodline.S02E08.2160p.WEBRip.X264-DEFLATE
Bloodline.S02E08.2160p.WEBRip.X264-DEFLATE.mkv
Bloodline.S02E09.2160p.WEBRip.X264-DEFLATE
Bloodline.S02E09.2160p.WEBRip.X264-DEFLATE.mkv
Bloodline.S02E10.2160p.WEBRip.X264-DEFLATE
Bloodline.S02E10.2160p.WEBRip.X264-DEFLATE.mkv
_unpackerred
```

If I then go into the first folder, for example,

```offspring@CloudSeedbox:/mnt/local/downloads/torrents/rutorrent/completed/sonarr4k/Bloodline.S02.2160p.WEBRip.X264-DEFLATE/Bloodline.S02E01.2160p.WEBRip.X264-DEFLATE$ ls
bloodline.s02e01.2160p.webrip.x264-deflate.nfo
bloodline.s02e01.2160p.webrip.x264-deflate.r00
bloodline.s02e01.2160p.webrip.x264-deflate.r01
bloodline.s02e01.2160p.webrip.x264-deflate.r02
bloodline.s02e01.2160p.webrip.x264-deflate.r03
bloodline.s02e01.2160p.webrip.x264-deflate.r04
bloodline.s02e01.2160p.webrip.x264-deflate.r05
bloodline.s02e01.2160p.webrip.x264-deflate.r06
bloodline.s02e01.2160p.webrip.x264-deflate.r07
bloodline.s02e01.2160p.webrip.x264-deflate.r08
bloodline.s02e01.2160p.webrip.x264-deflate.r09
bloodline.s02e01.2160p.webrip.x264-deflate.r10
bloodline.s02e01.2160p.webrip.x264-deflate.r11
bloodline.s02e01.2160p.webrip.x264-deflate.r12
bloodline.s02e01.2160p.webrip.x264-deflate.r13
bloodline.s02e01.2160p.webrip.x264-deflate.r14
bloodline.s02e01.2160p.webrip.x264-deflate.r15
bloodline.s02e01.2160p.webrip.x264-deflate.r16
bloodline.s02e01.2160p.webrip.x264-deflate.r17
bloodline.s02e01.2160p.webrip.x264-deflate.r18
bloodline.s02e01.2160p.webrip.x264-deflate.r19
bloodline.s02e01.2160p.webrip.x264-deflate.r20
bloodline.s02e01.2160p.webrip.x264-deflate.r21
bloodline.s02e01.2160p.webrip.x264-deflate.r22
bloodline.s02e01.2160p.webrip.x264-deflate.r23
bloodline.s02e01.2160p.webrip.x264-deflate.r24
bloodline.s02e01.2160p.webrip.x264-deflate.r25
bloodline.s02e01.2160p.webrip.x264-deflate.r26
bloodline.s02e01.2160p.webrip.x264-deflate.r27
bloodline.s02e01.2160p.webrip.x264-deflate.r28
bloodline.s02e01.2160p.webrip.x264-deflate.r29
bloodline.s02e01.2160p.webrip.x264-deflate.r30
bloodline.s02e01.2160p.webrip.x264-deflate.r31
bloodline.s02e01.2160p.webrip.x264-deflate.r32
bloodline.s02e01.2160p.webrip.x264-deflate.r33
bloodline.s02e01.2160p.webrip.x264-deflate.r34
bloodline.s02e01.2160p.webrip.x264-deflate.r35
bloodline.s02e01.2160p.webrip.x264-deflate.r36
bloodline.s02e01.2160p.webrip.x264-deflate.r37
bloodline.s02e01.2160p.webrip.x264-deflate.r38
bloodline.s02e01.2160p.webrip.x264-deflate.r39
bloodline.s02e01.2160p.webrip.x264-deflate.r40
bloodline.s02e01.2160p.webrip.x264-deflate.r41
bloodline.s02e01.2160p.webrip.x264-deflate.r42
bloodline.s02e01.2160p.webrip.x264-deflate.r43
bloodline.s02e01.2160p.webrip.x264-deflate.r44
bloodline.s02e01.2160p.webrip.x264-deflate.r45
bloodline.s02e01.2160p.webrip.x264-deflate.r46
bloodline.s02e01.2160p.webrip.x264-deflate.r47
bloodline.s02e01.2160p.webrip.x264-deflate.r48
bloodline.s02e01.2160p.webrip.x264-deflate.r49
bloodline.s02e01.2160p.webrip.x264-deflate.r50
bloodline.s02e01.2160p.webrip.x264-deflate.r51
bloodline.s02e01.2160p.webrip.x264-deflate.r52
bloodline.s02e01.2160p.webrip.x264-deflate.r53
bloodline.s02e01.2160p.webrip.x264-deflate.r54
bloodline.s02e01.2160p.webrip.x264-deflate.r55
bloodline.s02e01.2160p.webrip.x264-deflate.r56
bloodline.s02e01.2160p.webrip.x264-deflate.r57
bloodline.s02e01.2160p.webrip.x264-deflate.r58
bloodline.s02e01.2160p.webrip.x264-deflate.r59
bloodline.s02e01.2160p.webrip.x264-deflate.r60
bloodline.s02e01.2160p.webrip.x264-deflate.r61
bloodline.s02e01.2160p.webrip.x264-deflate.r62
bloodline.s02e01.2160p.webrip.x264-deflate.r63
bloodline.s02e01.2160p.webrip.x264-deflate.r64
bloodline.s02e01.2160p.webrip.x264-deflate.r65
bloodline.s02e01.2160p.webrip.x264-deflate.r66
bloodline.s02e01.2160p.webrip.x264-deflate.r67
bloodline.s02e01.2160p.webrip.x264-deflate.r68
bloodline.s02e01.2160p.webrip.x264-deflate.r69
bloodline.s02e01.2160p.webrip.x264-deflate.r70
bloodline.s02e01.2160p.webrip.x264-deflate.r71
bloodline.s02e01.2160p.webrip.x264-deflate.r72
bloodline.s02e01.2160p.webrip.x264-deflate.r73
bloodline.s02e01.2160p.webrip.x264-deflate.r74
bloodline.s02e01.2160p.webrip.x264-deflate.r75
bloodline.s02e01.2160p.webrip.x264-deflate.r76
bloodline.s02e01.2160p.webrip.x264-deflate.r77
bloodline.s02e01.2160p.webrip.x264-deflate.r78
bloodline.s02e01.2160p.webrip.x264-deflate.r79
bloodline.s02e01.2160p.webrip.x264-deflate.r80
bloodline.s02e01.2160p.webrip.x264-deflate.r81
bloodline.s02e01.2160p.webrip.x264-deflate.r82
bloodline.s02e01.2160p.webrip.x264-deflate.r83
bloodline.s02e01.2160p.webrip.x264-deflate.rar
bloodline.s02e01.2160p.webrip.x264-deflate.sfv
```

So for some reason unpackerr didn't move the files back to the root folder, but instead left them up one directory.

**Comment by davidnewhall** [comment] 2020-11-24 22:34
You'll need to share logs for me to understand what happened. Please be specific about the problem. "didn't move the files back to the root folder" is not specific enough for me to understand the issue you're having. Which files do you expect it to move, and to which folder? Please provide the logs so I know what it did.

**Comment by BRTPOB** [comment] 2020-11-24 22:40
Sure. I expected the tool to move the .rar files back to the folder with its name, as you said it should do. What I mean by that is: I expected the .mkv files to be moved from the root folder of Bloodline.S02.2160p.WEBRip.x264-DEFLATE back to their proper folders, which is what you said it would do previously. So the .mkv files should not be in the Bloodline.S02.2160p.WEBRip.x264-DEFLATE folder, but rather in each of the episodic folders such as Bloodline.S02E01.2160p.WEBRip.x264-DEFLATE, Bloodline.S02E02.2160p.WEBRip.x264-DEFLATE, etc.

The logs are 19 megs, since I've been running with debug since I got it setup. Let me figure out where the important section is and parse it down so that there's not a ton of extraneous data.

**Comment by davidnewhall** [comment] 2020-11-24 22:54
>  I expected the tool to move the .rar files

The tool does not move rar files. It only moves files that were inside the rar files; such as an mkv file. I would expect the mkv files to be moved into the same folder as the rar files, but now I'm wondering if you're using the `folder` feature instead of the `sonarr` probe. The folder feature may work differently with nested sub folders.

Did you set this up with a `folder` watcher, or are you probing Sonarr?

**Comment by BRTPOB** [comment] 2020-11-24 23:11
Sorry, I meant mkv not rar. I'm probing Sonarr. I just noticed, while chopping the log down to a much more manageable size, that this error popped up:

```
2020/11/24 20:23:12.955949 logs.go:65: [Unpackerr] Queue: [0 waiting] [0 queued] [1 extracting] [6 extracted] [0 imported] [0 failed] [1 deleted], Totals: [1 restarts] [107 finished]
2020/11/24 20:23:38.353087 start.go:79: Error: Reading path '/downloads/completed/sonarr4k/Bloodline.S02.2160p.WEBRip.X264-DEFLATE_unpackerred': open /downloads/completed/sonarr4k/Bloodline.S02.2160p.WEBRip.X264-DEFLATE_unpackerred: no such file or directory
2020/11/24 20:23:38.353125 start.go:85: [DEBUG] Extracting File: /downloads/completed/sonarr4k/Bloodline.S02.2160p.WEBRip.X264-DEFLATE/Bloodline.S02E06.2160p.WEBRip.X264-DEFLATE/bloodline.s02e06.2160p.webrip.x264-deflate.rar to /downloads/completed/sonarr4k/Bloodline.S02.2160p.WEBRip.X264-DEFLATE_unpackerred
2020/11/24 20:23:38.353135 start.go:79: Error: Reading path '/downloads/completed/sonarr4k/Bloodline.S02.2160p.WEBRip.X264-DEFLATE_unpackerred': open /downloads/completed/sonarr4k/Bloodline.S02.2160p.WEBRip.X264-DEFLATE_unpackerred: no such file or directory
```

Which is odd, because if I go into that folder, I see/saw it.
[chopped_upload_unpackerr.zip](https://github.com/davidnewhall/unpackerr/files/5593316/chopped_upload_unpackerr.zip)

**Comment by davidnewhall** [comment] 2020-11-24 23:18
Mulling on this. Give me a few.

**Comment by davidnewhall** [comment] 2020-11-24 23:36
There's got to be a bug here. It looks like it got stuck in a loop and began decompressing the same things multiple times. I think the multiple episodes in one pack triggered _every episode to be extracted_ x (times) _every episode_. Still trying to figure out what happened. This is a lot of logs over a huge amount of time. At one point I see it took 9 hours to decompress this one folder, which is where I get the "loop" theory.

**Comment by davidnewhall** [comment] 2020-11-24 23:44
I'm afraid you may have snipped out some log lines I need. I can't find any lines with this content:
```
Extracting File: /downloads/completed/radarr4k/Blood
```

I can see how the extraction ended, and it looks "wrong." I need to see how it started. How many times did you restart the app? Did it try to extract the items every time? Does nearly 10 hours to extract 237GB seem right? [I have no idea]

**Comment by BRTPOB** [comment] 2020-11-25 00:08
I still have the unedited log, it's just 19 megs tarred, and like 250 megs unpacked so I didn't want to hammer a system with that much data. I didn't restart the app, at all. I just let it run.

No, 9 hours seems...insane...for 237gb.

The fix was simply to create a symlink for Sonarr to find the files and then import them, since I had moved the folder at one point prior to the download completing so that it would properly be imported by Sonarr.

**Comment by davidnewhall** [comment] 2020-11-25 00:11
tbf, it extracted like 30 others things in that 9 hours... haha

Can you look in your bash history for that symlink command you used?

Can you `grep -iE 'error|bloodline' unpackerr.log > new.log` and send me that zipped up? My email will take files up to 20mb; my address is in my first reply on this thread.

**Comment by BRTPOB** [comment] 2020-11-25 07:14
The symlink command was
```
ln -s /mnt/local/downloads/torrents/rutorrent/completed/sonarr4k/Bloodline.S02.2160p.WEBRip.X264-DEFLATE/ .
```
Log file e-mailed.

**Comment by davidnewhall** [comment] 2020-11-25 07:36
These logs are great, thank you! What is `parallel` set to?
`grep -i parallel unpackerr.log` if you don't mind!

**Comment by BRTPOB** [comment] 2020-11-25 07:51
```
offspring@machine:/opt/unpackerr$ grep -i parallel unpackerr.log
2020/11/22 01:26:28  => Parallel: 1
2020/11/22 01:48:10  => Parallel: 1
2020/11/22 01:49:29  => Parallel: 1
2020/11/22 01:50:15  => Parallel: 1
2020/11/22 01:55:01.869529 logs.go:106:  => Parallel: 1
2020/11/22 02:05:13.760454 logs.go:106:  => Parallel: 1
2020/11/22 02:05:38.719733 logs.go:106:  => Parallel: 1
2020/11/22 10:58:06.304475 logs.go:106:  => Parallel: 5
2020/11/22 16:46:12.895560 logs.go:106:  => Parallel: 5
```

**Comment by davidnewhall** [comment] 2020-11-25 08:27
- whew. I was sure hoping you set parallel higher than 1, or there was yet another bug.
- So, you've found a bug, but I'm not sure the bug you found - that worries me - is the same problem you originally reported. 
- There is a second "display-only" bug in the `Renamed Temp File` log line. The two paths are always printed the same, this really confused me for a while. ([fixed](https://github.com/golift/xtractr/commit/c637d43c7191b5ee0d6384ed5877a269e93894b3))
- Your original report was that files were not being moved back into "the correct folder."
- The bug you found seems to be triggered when the connection to an *arr app is lost. Here's how it was trigged:
  - Extraction begins.
  - A connection to Sonarr fails. This "empties" the internal queue.
  - When the queue was emptied this item was marked `imported` even though it was still extracting. ([fixed](https://github.com/davidnewhall/unpackerr/commit/3f4948b9b61b53057341bc616478c50495e22c98))
  - Another connection to Sonarr succeed and the item came back.
  - The item was immediately reset, re-queued, and began extracting a second time.
  - This process repeated a 3rd time and the app extracted all 10 files 3 times each for 30 total extractions over a ~10 hour period.
  - Since you had parallel set to 5, other items extracted during this time as well.


Overall, despite the weird behavior, it looks like it worked and copied the mkv files back into the root `Bloodline.S02.2160p.WEBRip.X264-DEFLATE` folder.

Questions:
- In which folder did you find the extracted mkv files?
- Did Sonarr import them automatically? [doesn't seem like it did]

**Comment by davidnewhall** [comment] 2020-11-25 08:34
I re-read your original messages and I now know what is going on. I think this is a bug in Sonarr and it should import the mkv files from the root folder. @austinwbest - What do you think?

**Comment by BRTPOB** [comment] 2020-11-25 10:11
Unpackerr actually didn't move the files, I did. Then no, Sonarr didn't import them, I had to manually do it through the Sonarr UI. The extracted files were in the root Bloodline.S02.2160p folder, rather than the individual episodic subfolders.

**Comment by davidnewhall** [comment] 2020-11-25 10:31
Yup, it's currently designed to put all extracted things into that root folder. When I wrote this, I was trying to grab subs I subs/ folders and stuff. I didn't anticipate seasons/episodes like that, and so far it's never come up. I made a lot of changes to the `xtractr` library to deal with this, and I have to do a good bit of testing to make sure I didn't break anything.

Appreciate you working with me to figure this out!

**Comment by BRTPOB** [comment] 2020-11-25 10:32
No worries, like I said I really like the tool and it's worked out for my needs. Finding bugs is kind of a thing I used to do professionally, and as you can tell, I still find them for fun with other projects.

**Comment by davidnewhall** [comment] 2020-11-25 10:46
I posted a new beta release. The docker tag is almost done building and the binaries/package should be available within an hour or so. Give it a try if you're adventurous.

**Comment by austinwbest** [comment] 2020-11-25 12:39
> I re-read your original messages and I now know what is going on. I think this is a bug in Sonarr and it should import the mkv files from the root folder. @austinwbest - What do you think? See [this comment](https://github.com/davidnewhall/unpackerr/issues/64#issuecomment-733247049). I feel like that's something Sonarr should import.
> 
> EDIT: This is not a situation I've seen before, and I'm puzzled. Looking at my code, it's always behaved this way, and changing it a good bit of work. I think it's a good change though and I'll work on it.

Are you referring to the queue being empty? That happens on a restart & takes a minute (literally) to repopulate. It's the monitored downloads task. You can get around it but not without an extra api call

**Comment by austinwbest** [comment] 2020-11-25 13:18
> Yup, it's currently designed to put all extracted things into that root folder. When I wrote this, I was trying to grab subs in `subs/` folders and stuff. I didn't anticipate seasons/episodes like that, and so far it's never come up. I made a lot of changes to the `xtractr` library to deal with this, and I have to do a good bit of testing to make sure I didn't break anything.
> 
> Appreciate you working with me to figure this out!

Seems you have sorted it out but yea, that is a problem. If the rar files are inside folders then they would have to be extracted to that folder for *arr to find them.

**Comment by BRTPOB** [comment] 2020-11-25 15:35
Running the new version, it seems to constantly be restarting the docker container, and for some reason it only starts to unpack the Lion King movie, then stop. When I looked at the file itself, it was like 580kb. I was able to manually extract it and Radarr imported the file, but still odd. Here's the log: https://mactaggart.eskimomafia.com/selif/unpackerr.log

**Comment by davidnewhall** [comment] 2020-11-25 17:26
It's crashing it seems, and the crash isn't in the logs, it'll be in the console `(docker logs <container id>`).
Try the `master` docker tag.

**Comment by BRTPOB** [comment] 2020-11-25 17:30
2020/11/25 20:29:28.274273 handlers.go:133: Extraction Started: The.Lion.the.Witch.and.the.Wardrobe.1979.iNTERNAL.DVDRip.XviD-8BaLLRiPS, items in queue: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7f6dd1]

goroutine 24 [running]:
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).sendWebhooks(0xc000108440, 0xc000076320)
	/unpackerr/pkg/unpackerr/webhook.go:91 +0x321
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).updateQueueStatus(0xc000108440, 0xc00009cdd8, 0x2a)
	/unpackerr/pkg/unpackerr/folder.go:344 +0x19a
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).handleXtractrCallback(0xc000108440, 0xc0001302c0)
	/unpackerr/pkg/unpackerr/handlers.go:134 +0x540
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).Run(0xc000108440)
	/unpackerr/pkg/unpackerr/start.go:175 +0x289
created by github.com/davidnewhall/unpackerr/pkg/unpackerr.Start
	/unpackerr/pkg/unpackerr/start.go:127 +0x6f7
2020/11/25 20:29:28.283801 start.go:111: Unpackerr v0.7.2-beta6- Starting! (PID: 2322) 2020-11-25 20:29:28.283786399 +0300 EEST m=+0.001436984

**Comment by davidnewhall** [comment] 2020-11-25 17:30
Perfect thanks. Fixed in `master`.

**Comment by davidnewhall** [comment] 2020-11-25 18:14
I cut a beta7 release which should work. I've been running it all night and seems fine so far. Once Travis-CI decides to build it, there will be files added to the release. For now, you can use the docker tag to get it (Docker builds a lot faster than Travis).

Question: DO you use Qbitorrent? If not, what is your download client?

**Comment by BRTPOB** [comment] 2020-11-25 18:16
Nope. rTorrent with the ruTorrent webui.

**Comment by davidnewhall** [comment] 2020-11-25 18:19
What version of sonarr? v0.2 or v3?

**Comment by BRTPOB** [comment] 2020-11-25 18:20
Sonarr is v3, Radarr is v2 and v3 depending on FullHD or 4K.

**Comment by davidnewhall** [comment] 2020-11-25 23:45
A working beta version is available now. Please try it out and let me know how it works out for you. https://github.com/davidnewhall/unpackerr/releases/tag/v0.7.2-beta7

On docker: `docker pull golift/unpackerr:0.7.2-beta7`

**Comment by BRTPOB** [comment] 2020-11-26 00:06
Grabbed and pulled/running. Will probably need to wait til tomorrow to find another pack to test against, but it shouldn't take long.

**Comment by davidnewhall** [comment] 2020-11-26 00:10
For sure, I tried to find a few folks to test. it takes time for this thing to do stuff...

**Comment by BRTPOB** [comment] 2020-11-26 00:11
heh true, but it's more that it's just past midnight here so when I wake up I'll go searching for some packs to screw with.

**Comment by BRTPOB** [comment] 2020-11-26 00:11
That was the wrong click. Whoops.

**Comment by BRTPOB** [comment] 2020-11-26 14:24
Here's a log from today: https://mactaggart.eskimomafia.com/selif/unpackerr1.log. I was able to test a pack, and it worked, but individual files are causing it to break.

**Comment by austinwbest** [comment] 2020-11-26 16:15
Is this still related to sonarr & individual episodes not being imported? If so can you enable trace in sonarr, clear the logs, hit the refresh downloads task & attach the log?

I also highly recommended v3 for sonarr

**Comment by BRTPOB** [comment] 2020-11-26 16:16
Yeah, it is. I'm already using Sonarr v3. It's Radarr that I'm mixing/matching.

**Comment by austinwbest** [comment] 2020-11-26 17:23
Gotcha, well throw a sonarr log up there and I'll see if I can help

**Comment by BRTPOB** [comment] 2020-11-26 19:43
So looking at the logs, and my services I think this case it's not specifically Sonarr causing issues. Looks like unpackerr extracted a movie into the Subs/ directory, and that's causing stuff to be stuck in "Pending Import". I'm running Sonarr with trace watching the logs fly past but haven't seen anything stick out related to that.

**Comment by davidnewhall** [comment] 2020-11-26 20:58
Relevant logs:
```
2020/11/26 13:59:11.038083 handlers.go:133: Extraction Started: Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW, items in queue: 0
2020/11/26 13:59:11.038152 queue.go:211: [DEBUG] Extracting File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/snow-toy.story.of.terror.2013.1080p.bluray.x264.rar to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred
2020/11/26 13:59:31.697278 files.go:148: Error: Renaming Temp File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred/_unpackerred to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/_unpackerred: (refusing to overwrite existing file)
2020/11/26 13:59:31.697376 files.go:162: [DEBUG] Renamed Temp File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred/snow-toy.story.of.terror.2013.1080p.bluray.x264.mkv -> /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/snow-toy.story.of.terror.2013.1080p.bluray.x264.mkv
2020/11/26 13:59:31.697397 queue.go:211: [DEBUG] Extracting File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/Subs/snow-toy.story.of.terror.2013.1080p.bluray.x264.rar to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred
2020/11/26 13:59:32.454571 files.go:148: Error: Renaming Temp File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred/_unpackerred to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/Subs/_unpackerred: (refusing to overwrite existing file)
2020/11/26 13:59:32.454619 files.go:148: Error: Renaming Temp File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred/snow-toy.story.of.terror.2013.1080p.bluray.x264.sub to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/Subs/snow-toy.story.of.terror.2013.1080p.bluray.x264.sub: (refusing to overwrite existing file)
2020/11/26 13:59:32.454628 queue.go:211: [DEBUG] Extracting File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/Subs/snow-toy.story.of.terror.2013.1080p.bluray.x264-subs.rar to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred
2020/11/26 13:59:32.611566 queue.go:211: [DEBUG] Extracting File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred/snow-toy.story.of.terror.2013.1080p.bluray.x264.rar to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred
2020/11/26 13:59:32.880778 files.go:148: Error: Renaming Temp File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred/_unpackerred to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/Subs/_unpackerred: (refusing to overwrite existing file)
2020/11/26 13:59:32.880820 files.go:148: Error: Renaming Temp File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred/snow-toy.story.of.terror.2013.1080p.bluray.x264.idx to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/Subs/snow-toy.story.of.terror.2013.1080p.bluray.x264.idx: (refusing to overwrite existing file)
2020/11/26 13:59:32.880835 files.go:148: Error: Renaming Temp File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred/snow-toy.story.of.terror.2013.1080p.bluray.x264.rar to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/Subs/snow-toy.story.of.terror.2013.1080p.bluray.x264.rar: (refusing to overwrite existing file)
2020/11/26 13:59:32.880850 files.go:148: Error: Renaming Temp File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred/snow-toy.story.of.terror.2013.1080p.bluray.x264.sub to /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/Subs/snow-toy.story.of.terror.2013.1080p.bluray.x264.sub: (refusing to overwrite existing file)
2020/11/26 13:59:33.067180 files.go:183: Deleted (recursively): /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred
2020/11/26 13:59:33.067232 handlers.go:139: Extraction Finished: Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW => elapsed: 22s, archives: 3, extra archives: 1, files extracted: 8, wrote: 1518MiB
```

Every line had an error (odd that all the extracted files already existed), except this one:
```
Renamed Temp File: /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW_unpackerred/snow-toy.story.of.terror.2013.1080p.bluray.x264.mkv -> /downloads/completed/radarr/Toy.Story.Of.Terror.2013.1080p.BluRay.x264-SNOW/snow-toy.story.of.terror.2013.1080p.bluray.x264.mkv
```

That looks to me like the movie was copied into the correct path. What is the message in Sonarr about why it wont import?

It then "goes away and comes back" (which could mean the connection to sonarr was interrupted. This triggers it to extract again. I think _that_ is a minor bug I can fix on my end, so it wont extract again after it already did successfully.

**There are a lot of logs here. What's the name of the pack you saw it put a movie into Subs/?**

**Comment by davidnewhall** [comment] 2020-11-26 21:50
You can jump in my discord. This thread is getting long, Might be easier to finish this off in a chat session. https://discord.gg/tVMPw6mCZw

I'll be around later after I stuff myself with dead birds and mushy bread.

**Comment by BRTPOB** [comment] 2020-11-26 22:03
Sure thing. I just finished myself with dead birds and mashed taters.

**Closed** 2020-12-01 07:25 UTC
Labels: bug
