### ISSUE TITLE
Possible bug - "completed file still waiting"

### ISSUE THREAD

**Issue by PierreDurrr** [davidnewhall/unpackerr#126] opened 2021-05-19 18:14 UTC
Just like [issue #123](https://github.com/davidnewhall/unpackerr/issues/123) it seems to not extract if there is a sample file.

Here is my docker-compose file :
[https://pastebin.com/JWjW678w](https://pastebin.com/JWjW678w)

And here is my log :
[https://pastebin.com/Xt45Uufu](https://pastebin.com/Xt45Uufu)

**Comment by davidnewhall** [comment] 2021-05-19 18:16
It's not a bug, just a configuration problem.

Your files are not here: `/share/syno/_en_attente/Item.Title.Name` - where are they?

**Comment by PierreDurrr** [comment] 2021-05-19 18:23
I can confirm they are, it is working for others files

**Comment by davidnewhall** [comment] 2021-05-19 18:24
Show me a log entries for one that worked then I can show you how to fix the config.

**Comment by PierreDurrr** [comment] 2021-05-19 18:28
Will paste a log when my newt download is finished

**Comment by davidnewhall** [comment] 2021-05-19 18:30
Do you have the full path to this folder? (from your log) - `Family.Guy.S05E03.FRENCH.720p.WEB.H264-AVON`

**Comment by davidnewhall** [comment] 2021-06-05 05:12
Got any updates?

**Comment by joelang1699** [comment] 2021-06-19 19:09
Dave

I've had a few torrents recently that include SMAPLE files as part of the pre-extraction torrent. If it's an especially large torrent the sonarr/radarr reports "waiting to import" and quotes the sample files. However once all files are extracted and imported properly the *arr's forget about this and everything is back to normal.

**Comment by davidnewhall** [comment] 2021-06-19 23:46
@joelang1699 Are you reporting a problem you need help with? it sounds like you may be. Please open a new issue, and attach logs and application configuration. We can fix you up.

**Comment by joelang1699** [comment] 2021-06-20 04:28
No problem. I was just adding some insight as there's a few of the "sample" threads open.

**Comment by davidnewhall** [comment] 2021-06-20 05:13
In that case, thank you! :) 

I'm very familiar with the sample problem. Unpackerr makes every attempt to find files, even if the `paths` variables are not set correctly. It even parses that error you see when sonarr or radarr can't import something. Sometimes the error has the path in it. When there is a sample. the path is not in the error. This is when people notice "when there's a sample file it wont extract." My mind translates that to "I have the wrong paths configured," and I try to get logs and config info so I can help the users correct their paths. 

The last couple releases should actually fix this particular problem. I switched the Radarr and Sonarr `queue` api endpoint to the `v3` versions, and these actually include a `path` key. We now use that path key instead of the error message. Should work the same way, but a sample wont break it.

That said, I'm going to close this issue. If you're experiencing problems with extraction, please update to the latest version. Thanks!

**Closed by davidnewhall** 2021-06-20 05:13 UTC
